Controllers/MAS_ContactController.cs
using AddressBook.DAL;
using AddressBook.Models;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Data.SqlClient;

namespace AddressBook.Controllers
{
    public class MAS_ContactController : Controller
    {
        private IConfiguration Configuration;

        public MAS_ContactController(IConfiguration _configuration)
        {
            Configuration = _configuration;
        }

        CON_DAL dalCON = new CON_DAL();

        public ActionResult Index()
        {
            string connectionString = this.Configuration.GetConnectionString("SQL_AddressBook");
            DataTable dt = dalCON.PR_MAS_Contact_SelectAll(connectionString);
            return View("MAS_ContactList",dt);
        }


        public ActionResult Delete(int ContactID)
        {
            String connectionString = this.Configuration.GetConnectionString("SQL_AddressBook");
            if (Convert.ToBoolean(dalCON.PR_MAS_Contact_Delete(connectionString, ContactID)))
                return RedirectToAction("Index");
            return View("Index");
        }


        public IActionResult Add(int? ContactID)
        {
            String connectionstr7 = this.Configuration.GetConnectionString("SQL_AddressBook");
            DataTable dt7 = dalCON.PR_ContactCategory_SelectByDropdownList(connectionstr7);
            
            List<MST_ContactCategoryDropDownModel> list7 = new List<MST_ContactCategoryDropDownModel>();
            foreach (DataRow dr in dt7.Rows)
            {
                MST_ContactCategoryDropDownModel modelMST_ContactCategory = new MST_ContactCategoryDropDownModel();
                modelMST_ContactCategory.ContactCategoryID = Convert.ToInt32(dr["ContactCategoryID"]);
                modelMST_ContactCategory.ContactCategoryName = (string)dr["ContactCategoryName"];
                list7.Add(modelMST_ContactCategory);
            }
            ViewBag.ContactCategoryList = list7;

            String str6 = this.Configuration.GetConnectionString("SQL_AddressBook");
            DataTable dt6 = new DataTable();
            SqlConnection conn6 = new SqlConnection(str6);
            conn6.Open();
            SqlCommand cmd6 = conn6.CreateCommand();
            cmd6.CommandType = CommandType.StoredProcedure;
            cmd6.CommandText = "PR_LOC_Country_SelectForDropDown";
            SqlDataReader objSDR6 = cmd6.ExecuteReader();
            dt6.Load(objSDR6);
            conn6.Close();

            List<Areas.Models.LOC_CountryDropDownModel> list6 = new List<Areas.Models.LOC_CountryDropDownModel>();
            foreach (DataRow dr in dt6.Rows)
            {
                Areas.Models.LOC_CountryDropDownModel modelLOC_CountryDropDown = new Areas.Models.LOC_CountryDropDownModel();
                modelLOC_CountryDropDown.CountryID = Convert.ToInt32(dr["CountryID"]);
                modelLOC_CountryDropDown.CountryName = (string)dr["CountryName"];
                list6.Add(modelLOC_CountryDropDown);
            }
            ViewBag.CountryList = list6;

            List<Areas.Models.LOC_StateDropDownModel> list4 = new List<Areas.Models.LOC_StateDropDownModel>();
            ViewBag.StateList = list4;

            List<LOC_CityDropDownModel> list5 = new List<LOC_CityDropDownModel>();
            ViewBag.CityList = list5;

            
            if(ContactID!=null)
            {
                String str5 = this.Configuration.GetConnectionString("SQL_AddressBook");
                DataTable dt = dalCON.PR_MAS_Contact_SelectByPK(str5, ContactID);
                MAS_ContactModel modelMAS_Contact = new MAS_ContactModel();

                foreach(DataRow dr in dt.Rows)
                {
                    modelMAS_Contact.ContactID = Convert.ToInt32(dr["ContactID"]);
                    modelMAS_Contact.ContactName = dr["ContactName"].ToString();
                    modelMAS_Contact.ContactAddress = dr["ContactAddress"].ToString();
                    modelMAS_Contact.CountryID = Convert.ToInt32(dr["CountryID"]);
                    modelMAS_Contact.StateID = Convert.ToInt32(dr["StateID"]);
                    modelMAS_Contact.CityID = Convert.ToInt32(dr["CityID"]);
                    modelMAS_Contact.ContactPincode = Convert.ToInt32(dr["ContactPincode"]);
                    modelMAS_Contact.ContactMobile = dr["ContactMobile"].ToString();
                    modelMAS_Contact.ContactEmail = dr["ContactEmail"].ToString();
                    modelMAS_Contact.ContactDOB = Convert.ToDateTime(dr["ContactDOB"]);
                    modelMAS_Contact.ContactLinkedIN = dr["ContactLinkedIN"].ToString();
                    modelMAS_Contact.ContactGender = dr["ContactGender"].ToString();
                    modelMAS_Contact.ContactTypeOfProfession = dr["ContactTypeOfProfession"].ToString();
                    modelMAS_Contact.ContactCompanyName = dr["ContactCompanyName"].ToString();
                    modelMAS_Contact.ContactDesignation = dr["ContactDesignation"].ToString();
                    modelMAS_Contact.ModificationDate = Convert.ToDateTime(dr["ModificationDate"]);
                    modelMAS_Contact.ContactCategoryID = Convert.ToInt32(dr["ContactCategoryID"]);
                }
                return View("MAS_ContactAddEdit",modelMAS_Contact);
            }
            return View("MAS_ContactAddEdit");
        }


        [HttpPost]
        public IActionResult Save(MAS_ContactModel modelMAS_Contact)
        {
            if (modelMAS_Contact.File != null)
            {
                string FilePath = "wwwroot\\Upload";
                string path = Path.Combine(Directory.GetCurrentDirectory(), FilePath);

                if (!Directory.Exists(path))
                    Directory.CreateDirectory(path);

                string fileNameWithPath = Path.Combine(path, modelMAS_Contact.File.FileName);
                modelMAS_Contact.PhotoPath = "" + FilePath.Replace("wwwroot\\", "/") + "/" + modelMAS_Contact.File.FileName;

                using (var stream = new FileStream(fileNameWithPath, FileMode.Create))

                {
                    modelMAS_Contact.File.CopyTo(stream);
                }

            }
            string connectionString = this.Configuration.GetConnectionString("SQL_AddressBook");
            SqlConnection conn = new SqlConnection(connectionString);
            conn.Open();
            SqlCommand objCmd = conn.CreateCommand();
            objCmd.CommandType = CommandType.StoredProcedure;
            if(modelMAS_Contact.ContactID == null)
            {
                objCmd.CommandText = "PR_MAS_Contact_Insert";
                objCmd.Parameters.Add("@CreationDate",SqlDbType.Date).Value = DBNull.Value;
            }
            else
            {
                objCmd.CommandText = "PR_MAS_Contact_UpdateByPK";
                objCmd.Parameters.Add("@ContactID",SqlDbType.Int).Value = modelMAS_Contact.ContactID;
            }
            objCmd.Parameters.Add("@ContactName",SqlDbType.VarChar).Value = modelMAS_Contact.ContactName;
            objCmd.Parameters.Add("@ContactAddress",SqlDbType.VarChar).Value = modelMAS_Contact.ContactAddress;
            objCmd.Parameters.Add("@ContactCategoryID",SqlDbType.Int).Value = modelMAS_Contact.ContactCategoryID;
            objCmd.Parameters.Add("@CountryID",SqlDbType.Int).Value = modelMAS_Contact.CountryID;
            objCmd.Parameters.Add("@StateID",SqlDbType.Int).Value = modelMAS_Contact.StateID;
            objCmd.Parameters.Add("@CityID",SqlDbType.Int).Value = modelMAS_Contact.CityID;
            objCmd.Parameters.Add("@ContactPincode",SqlDbType.VarChar).Value = modelMAS_Contact.ContactPincode;
            objCmd.Parameters.Add("@ContactMobile",SqlDbType.VarChar).Value = modelMAS_Contact.ContactMobile;
            objCmd.Parameters.Add("@ContactEmail",SqlDbType.VarChar).Value = modelMAS_Contact.ContactEmail;
            objCmd.Parameters.Add("@ContactDOB",SqlDbType.Date).Value = modelMAS_Contact.ContactDOB;
            objCmd.Parameters.Add("@ContactLinkedIN",SqlDbType.VarChar).Value = modelMAS_Contact.ContactLinkedIN;
            objCmd.Parameters.Add("@ContactGender",SqlDbType.VarChar).Value = modelMAS_Contact.ContactGender;
            objCmd.Parameters.Add("@ContactTypeOfProfession",SqlDbType.VarChar).Value = modelMAS_Contact.ContactTypeOfProfession;
            objCmd.Parameters.Add("@ContactCompanyName",SqlDbType.VarChar).Value = modelMAS_Contact.ContactCompanyName;
            objCmd.Parameters.Add("@ContactDesignation",SqlDbType.VarChar).Value = modelMAS_Contact.ContactDesignation;
            objCmd.Parameters.Add("@ModificationDate",SqlDbType.Date).Value = DBNull.Value;
            objCmd.Parameters.Add("@PhotoPath", SqlDbType.NVarChar).Value = modelMAS_Contact.PhotoPath;
            
             
            if(Convert.ToBoolean(objCmd.ExecuteNonQuery()))
            {
                if(modelMAS_Contact.ContactID == null)
                {
                    TempData["ContactInsetMsg"] = "Record Inserted Successfully";
                }
                else
                {
                    TempData["ContactInsetMsg"] = "Record Updated Successfully";
                }
            }
            conn.Close();
            
            return View("MAS_ContactAddEdit");
        }

        public ActionResult DropDownByState(int StateID)
        {
            String connectionstr = this.Configuration.GetConnectionString("SQL_AddressBook");
           
           
            SqlConnection conn1 = new SqlConnection(connectionstr);
            conn1.Open();
            SqlCommand cmd1 = conn1.CreateCommand();
            cmd1.CommandType = CommandType.StoredProcedure;
            cmd1.CommandText = "PR_LOC_City_SelectForDropDown";
            cmd1.Parameters.AddWithValue("@StateID", StateID);
            DataTable dt1 = new DataTable();
            SqlDataReader objSDR1 = cmd1.ExecuteReader();
            dt1.Load(objSDR1);
           

Areas/MAS_Contact/Views/MAS_Contact/MAS_ContactAddEdit.cshtml
@{
    ViewData["Title"] = "Contact Add/Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Multi_AddressBook.Areas.Models.MAS_ContactModel
<div class="row">
    <div class="col-md-12">
        <h3> @TempData["ContactInsertMsg"]</h3>
        <form method="post" enctype="multipart/form-data" role="form" asp-controller="MAS_Contact" asp-action="Save">
            @Html.HiddenFor(x=>x.ContactID)
            @Html.HiddenFor(x=>x.PhotoPath)
            <div class="form-group">
                <label>ContactName</label>
                <input type="text" asp-for="ContactName" class=form-control placeholder="Enter Contact Name" />
                <span asp-validation-for="ContactName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>ContactCategory</label>
                <select class="form-control" asp-for="ContactCategoryID" asp-items="@(new SelectList(ViewBag.ContactCategoryList,"ContactCategoryID","ContactCategoryName"))">
                    <option value="">Select ContactCategory</option>
                </select>
           </div>
            <div class="form-group">
                <label>ContactAddress</label>
                <input type="text" asp-for="ContactAddress" class=form-control placeholder="Enter Contact Address" />
                <span asp-validation-for="ContactAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>CountryName</label>
              <select class="form-control" asp-for="CountryID" asp-items="@(new SelectList(ViewBag.CountryList,"CountryID","CountryName"))" onchange="fnOnStateChange();">
                    <option value="">Select Country</option>*
                </select>
                <span asp-validation-for="CountryID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>StateName</label>
                <select class="form-control" asp-for="StateID" asp-items="@(new SelectList(ViewBag.StateList,"StateID","StateName"))" onchange="fnOnCityChange();">
                    <option value="">Select State</option>
                </select>
                <span asp-validation-for="StateID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>CityName</label>
                <select class="form-control" asp-for="CityID" asp-items="@(new SelectList(ViewBag.CityList,"CityID","CityName"))">
                    <option value="0">Select City</option>
                </select>
                <span asp-validation-for="CityID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Pincode</label>
                <input type="text" asp-for="ContactPincode" class=form-control placeholder="Enter Pincode" />
            </div>
            <div class="form-group">
                <label>Email</label>
                <input type="text" asp-for="ContactEmail" class=form-control placeholder="Enter Email" />
                <span asp-validation-for="ContactEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Mobile</label>
                <input type="text" asp-for="ContactMobile" class=form-control placeholder="Enter Mobile Number" />
                <span asp-validation-for="ContactMobile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Gender</label>
                <input type="text" asp-for="ContactGender" class=form-control placeholder="Enter Gender" />
            </div><div class="form-group">
                <label>DateofBirth</label>
                <input type="date" asp-for="ContactDOB" class=form-control placeholder="Enter DateofBirth" />
            </div>
            <div class="form-group">
                <label>Linkedin</label>
                <input type="text" asp-for="ContactLinkedIN" class=form-control placeholder="Enter Linkedin profile name" />
            </div>
            <div class="form-group">
                <label>Contact Type Of Profession</label>
                <input type="text" asp-for="ContactTypeOfProfession" class=form-control placeholder="Enter Contact Type Of Profession" />
            </div>
            <div class="form-group">
                <label>Contact CompanyName</label>
                <input type="text" asp-for="ContactCompanyName" class=form-control placeholder="Enter Contact CompanyName" />
            </div>
            <div class="form-group">
                <label>Contact Designation</label>
                <input type="text" asp-for="ContactDesignation" class=form-control placeholder="Enter Designation" />
            </div>
            <div class="form-group">
                <label>PhotoPath</label>
                <input class="form-control" type="file" asp-for="File" placeholder="Upload File"/>
            </div>
            <hr />
            <div class="center-button"><input class="btn btn-success" type="submit" value="Save"></div>
            <div class="center-button"><a asp-controller="MAS_Contact" asp-action="Index" class="btn btn-danger">Cancel</a></div>
        </form>
    </div>
</div>
@section Scripts
    {
    <script>
        function fnOnStateChange() {
            var CountryID = $("#CountryID").val();

            if (CountryID !== "") {
                $("#StateID").empty();
                $("#StateID").append($("<option></option>").val("").html("Select State"));
                $.ajax(
                    {
                        type: "POST",
                        contentType: "application/json; charset=utf-8",
                        url: "@Url.Action("DropDownByCountry","MAS_Contact")" + "?&CountryID=" + CountryID,
                        data: {},
                        dataType: "json",
                        success: function (Result) {
                            $.each(Result,
                                function (key, value) {
                                    $("#StateID").append($("<option></option>").val(value.stateID).html(value.stateName));
                                }
                            );
                        },
                        error: function (r) {
                            alert("Error While Loading DropDown");
                        }
                    }
                );
            }
            else {
                $("#StateID").empty();
                $("#StateID").append($("<option></option>").val("").html("Select State"));
            }
        }
    </script>
    <script>
        function fnOnCityChange() {
            var StateID = $("#StateID").val();

            if (StateID !== "") {
                $("#CityID").empty();
                $("#CityID").append($("<option></option>").val("").html("Select City"));
                $.ajax(
                    {
                        type: "POST",
                        contentType: "application/json; charset=utf-8",
                        url: "@Url.Action("DropDownByState","MAS_Contact")" + "?&StateID=" + StateID,
                        data: {},
                        dataType: "json",
                        success: function (Result) {
                            $.each(Result,
                                function (key, value) {
                                    $("#CityID").append($("<option></option>").val(value.cityID).html(value.cityName));
                                }
                            );
                        },
                        error: function (r) {
                            alert("Error While Loading DropDown");
                        }
                    }
                );
            }
            else {
                $("#CityID").empty();
                $("#CityID").append($("<option></option>").val("").html("Select City"));
            }
        }
    </script>

}

Areas/MAS_Contact/Views/MAS_Contact/MAS_ContactList.cshtml
@{
    ViewData["Title"] = "Country List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .img{
        width: 60px;
        height: 60px;
    }
    table {
        display: block;
        overflow-x: auto;
        white-space: nowrap;
    }
</style>
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css">
@using System.Data
@model DataTable

<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a asp-controller="Home" asp-action="Index"><i class="fa fa-home"></i>&nbsp;Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a asp-controller="MAS_Contact" asp-action="Index">Contact List</a>
            <i class="fa fa-circle"></i>
        </li>
    </ul>
</div>
<!-- BEGIN EXAMPLE TABLE PORTLET-->
<div class="portlet light bordered margin-top-10">
    <div class="portlet-title">
        <div class="caption font-dark">
            <i class="icon-settings font-dark"></i>
            <span class="caption-subject bold uppercase">Contact List</span>
        </div>
        <div class="actions">
            <div class="btn-group btn-group-devided">
                <a asp-controller="MAS_Contact" asp-action="Add" class="btn green"><i class="fa fa-plus"></i>&nbsp;Add Contact</a>
            </div>
        </div>
    </div>
    <div class="portlet-body">
        <div class="pull-right">
            <div id="sample_1_filter" class="dataTables_filter">
                <label>Search Any&nbsp;<input type="text" class="form-control input-sm input-small input-inline" id="sample_1"></label>
            </div>
        </div>

        
        <table class="table table-striped table-bordered table-hover table-header-fixed dataTable">
            <thead>
                <tr class="">
                    @*<th>Country ID</th>*@
                    <th class="text-center">Actions</th>
                    <th>ContactName</th>
                    <th>ContactCatagoryName</th>
                    <th>ContactAddress</th>
                    <th>ContactCountry</th>
                    <th>ContactState</th>
                    <th>ContactCity</th>
                    <th>ContactPincode</th>
                    <th>ContactMobile</th>
                    <th>ContactEmail</th>
                    <th>ContactDOB</th>
                    <th>ContactLinkedIN</th>
                    <th>ContactGender</th>
                    <th>ContactTypeOfProfession</th>
                    <th>ContactCompanyName</th>
                    <th>ContactDesignation</th>
                    <th>Photo</th>
                    <th class="text-center">Created</th>
                    <th class="text-center">Modified</th>
                </tr>
            </thead>
            <tbody id="sample_2">
                @foreach (DataRow dr in Model.Rows)
                {
                    <tr>
                        @*<td>@dr["CountryID"]</td>*@
                        <td class="text-center">
                            <form method="post" asp-controller="MAS_Contact" asp-action="Delete">
                                <input type="hidden" name="ContactID" value=" @Convert.ToInt32(dr["ContactID"].ToString())">
                                <button type="submit" class="btn btn-danger btn-xs" onclick="return fun4();"><i class="fa fa-close"></i></button>
                                <a class="btn btn-info btn-xs" asp-controller="MAS_Contact" asp-action="Add" asp-route-contactid="@Convert.ToInt32(dr["ContactID"])"><i class="fa fa-pencil"></i></a>
                            </form>
                        </td>
                        <td>@dr["ContactName"]</td>
                        <td>@dr["ContactCategoryName"]</td>&nbsp
                        <td>@dr["ContactAddress"]</td>
                        <td>@dr["CountryName"]</td>
                        <td>@dr["StateName"]</td>
                        <td>@dr["CityName"]</td>
                        <td>@dr["ContactPincode"]</td>
                        <td>@dr["ContactMobile"]</td>
                        <td>@dr["ContactEmail"]</td>
                        <td>@dr["ContactDOB"]</td>
                        <td>@dr["ContactLinkedIN"]</td>
                        <td>@dr["ContactGender"]</td>
                        <td>@dr["ContactTypeOfProfession"]</td>
                        <td>@dr["ContactCompanyName"]</td>
                        <td>@dr["ContactDesignation"]</td>
                        <td><img src=@dr["PhotoPath"] class="img" alt="img"></td>
                        <td class="text-center">@Convert.ToDateTime(dr["CreationDate"]).ToString("dd-MM-yyyy hh:mm:ss")</td>
                        <td class="text-center">@Convert.ToDateTime(dr["ModificationDate"]).ToString("dd-MM-yyyy hh:mm:ss")</td>
                    </tr>
                }
            </tbody>
        </table>
        
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
@section Scripts
    {
    <script>
        $(document).ready(function () {
            $("#sample_1").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#sample_2 tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
        function fun4() {
            if (confirm("Are you sure you want to delete")) {
                return true;
            }
            else {
                return false;
            }
        }
        $(document).ready(function () {
            $('#example').DataTable({
                scrollX: true,
            });
        });
    </script>
}