Areas/MST_ContactCategory/Controllers/MST_ContactCategoryController.cs
using Multi_AddressBook.DAL;
using Multi_AddressBook.BAL;
using Multi_AddressBook.Areas.Models;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Data.SqlClient;

namespace Multi_AddressBook.Areas.MST_ContactCategory.Controllers
{
    [CheckAccess]
    [Area("MST_ContactCategory")]
    [Route("MST_ContactCategory/[Controller]/[action]")]
    public class MST_ContactCategoryController : Controller
    {
        private IConfiguration Configuration;
        public MST_ContactCategoryController(IConfiguration _configuration)
        {
            Configuration = _configuration;
        }
        MAS_DAL dalCON = new MAS_DAL();
        public ActionResult Index()
        {
            DataTable dt = dalCON.PR_ContactCategory_SelectAll();
            return View("MST_ContactCategoryList", dt);
        }
        public ActionResult Delete(int ContactCategoryID)
        {
            String str = this.Configuration.GetConnectionString("SQL_AddressBook");
            SqlConnection conn = new SqlConnection(str);
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "PR_ContactCategory_DeleteByPK";
            cmd.Parameters.AddWithValue("@ContactCategoryID", ContactCategoryID);
            DataTable dt = new DataTable();
            cmd.ExecuteNonQuery();
            conn.Close();

            return RedirectToAction("Index");
        }
        public IActionResult Add(int? ContactCategoryID)
        {
            if (ContactCategoryID != null)
            {
                String str = this.Configuration.GetConnectionString("SQL_AddressBook");
                SqlConnection conn = new SqlConnection(str);
                conn.Open();
                SqlCommand cmd = conn.CreateCommand();
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.CommandText = "PR_ContactCategory_SelectByPK";
                cmd.Parameters.Add("@ContactCategoryID", SqlDbType.Int).Value = ContactCategoryID;
                DataTable dt = new DataTable();
                SqlDataReader objSDR = cmd.ExecuteReader();
                dt.Load(objSDR);
                MST_ContactCategoryModel modelMST_ContactCategory = new MST_ContactCategoryModel();
                foreach (DataRow dr in dt.Rows)
                {
                    modelMST_ContactCategory.ContactCategoryID = (Convert.ToInt32(dr["ContactCategoryID"]));
                    modelMST_ContactCategory.ContactCategoryName = (Convert.ToString(dr["ContactCategoryName"]));
                    modelMST_ContactCategory.CreationDate = (Convert.ToDateTime(dr["CreationDate"]));
                    modelMST_ContactCategory.ModificationDate = (Convert.ToDateTime(dr["ModificationDate"]));
                }
                return View("MST_ContactCategoryAddEdit", modelMST_ContactCategory);
            }
            return View("MST_ContactCategoryAddEdit");
        }
    
        [HttpPost]
        public ActionResult Save(MST_ContactCategoryModel modelMST_ContactCategory)
        {
            String str = this.Configuration.GetConnectionString("SQL_AddressBook");
            SqlConnection conn = new SqlConnection(str);
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            if (modelMST_ContactCategory.ContactCategoryID == null)
            {
                cmd.CommandText = "PR_ContactCategory_Insert";
                cmd.Parameters.Add("@CreationDate", SqlDbType.DateTime).Value = DBNull.Value;
            }
            else
            {
                cmd.CommandText = "PR_ContactCategory_UpdateByPK";
                cmd.Parameters.Add("@ContactCategoryID", SqlDbType.Int).Value = modelMST_ContactCategory.ContactCategoryID;
            } 
            cmd.Parameters.Add("@ContactCategoryName", SqlDbType.NVarChar).Value = modelMST_ContactCategory.ContactCategoryName;
            cmd.Parameters.Add("@ModificationDate", SqlDbType.DateTime).Value = DBNull.Value;

            cmd.ExecuteNonQuery();
            conn.Close();
            return RedirectToAction("Index");
        }
    }
}

Controllers/LOC_CountryController.cs
using AddressBook.DAL;
using AddressBook.Models;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Data.SqlClient;

namespace AddressBook.Controllers
{
    public class LOC_CountryController : Controller
    {
        private IConfiguration Configuration;
        public LOC_CountryController(IConfiguration _configuration)
        {
            Configuration = _configuration;
        }

        LOC_DAL dalLOC = new LOC_DAL();
        #region SelectAll
        public ActionResult Index()
        {
            String str = this.Configuration.GetConnectionString("SQL_AddressBook");
            DataTable dt = dalLOC.PR_LOC_Country_SelectAll(str);
            return View("LOC_CountryList", dt);
        }
        #endregion

        #region Delete
        public ActionResult Delete(int CountryID)
        {
            String str = this.Configuration.GetConnectionString("SQL_AddressBook");
            if (Convert.ToBoolean(dalLOC.PR_LOC_Country_Delete(str, CountryID)))
                return RedirectToAction("Index");
            return View("Index");
        }
        #endregion


        public IActionResult Add(int? CountryID)
        {
            if (CountryID != null)
            {
                String str = this.Configuration.GetConnectionString("SQL_AddressBook");
                DataTable dt = dalLOC.PR_LOC_Country_SelectByPK(str, CountryID);

                LOC_CountryModel modelLOC_Country = new LOC_CountryModel();
                foreach (DataRow dr in dt.Rows)
                {
                    modelLOC_Country.CountryID = (Convert.ToInt32(dr["CountryID"]));
                    modelLOC_Country.CountryName = (Convert.ToString (dr["CountryName"]));
                    modelLOC_Country.CountryCode = (Convert.ToString (dr["CountryCode"]));
                    modelLOC_Country.CreationDate = (Convert.ToDateTime(dr["CreationDate"]));
                    modelLOC_Country.ModificationDate = (Convert.ToDateTime(dr["ModificationDate"]));
                    //modelLOC_Country.PhotoPath = (Convert.ToString(dr["PhotoPath"]));
                }
                return View("LOC_CountryAddEdit", modelLOC_Country);
            }
            return View("LOC_CountryAddEdit");
        }
        [HttpPost]
        public IActionResult Save(LOC_CountryModel modelLoc_Country)
        {
            string connectionString = this.Configuration.GetConnectionString("SQL_AddressBook");
            SqlConnection conn = new SqlConnection(connectionString);
            conn.Open();
            SqlCommand objCmd = conn.CreateCommand();
            objCmd.CommandType = CommandType.StoredProcedure;
            if(modelLoc_Country.CountryID == null)
            {
                objCmd.CommandText = "PR_LOC_Country_Insert";
                objCmd.Parameters.Add("@CreationDate",SqlDbType.Date).Value = DBNull.Value;
            }
            else
            {
                objCmd.CommandText = "PR_LOC_Country_UpdateByPK";
                objCmd.Parameters.Add("@CountryID",SqlDbType.Int).Value = modelLoc_Country.CountryID;
            }
            objCmd.Parameters.Add("@CountryName",SqlDbType.VarChar).Value = modelLoc_Country.CountryName;
            objCmd.Parameters.Add("@CountryCode",SqlDbType.VarChar).Value = modelLoc_Country.CountryCode;
            objCmd.Parameters.Add("@ModificationDate",SqlDbType.Date).Value = DBNull.Value;
            
             
            if(Convert.ToBoolean(objCmd.ExecuteNonQuery()))
            {
                if(modelLoc_Country.CountryID == null)
                {
                    TempData["CountryInsetMsg"] = "Record Inserted Successfully";
                }
                else
                {
                    TempData["CountryInsetMsg"] = "Record Updated Successfully";
                }
            }
            conn.Close();
            
            return View("LOC_CountryAddEdit");
        }
        public ActionResult Search(int CountryID)
        {
            string str = this.Configuration.GetConnectionString("SQL_AddressBook");
            SqlConnection conn = new SqlConnection(str);
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "PR_LOC_Country_Search";
            cmd.Parameters.AddWithValue("@CountryName", Convert.ToString(HttpContext.Request.Form["CountryName"]));
            cmd.Parameters.AddWithValue("@CountryCode", Convert.ToString(HttpContext.Request.Form["CountryCode"]));
            /*cmd.Parameters.Add("@CountryName", SqlDbType.VarChar).Value = CountryName;
            cmd.Parameters.Add("@CountryCode", SqlDbType.VarChar).Value = CountryCode;*/
            DataTable dt = new DataTable();
            SqlDataReader objSDR = cmd.ExecuteReader();
            dt.Load(objSDR);

            return View("LOC_CountryList", dt);
        }
    }
}

Controllers/MST_ContactCategoryController.cs
using AddressBook.DAL;
using AddressBook.Models;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Data.SqlClient;

namespace AddressBook.Controllers
{
    public class MST_ContactCategoryController : Controller
    {
        private IConfiguration Configuration;
        public MST_ContactCategoryController(IConfiguration _configuration)
        {
            Configuration = _configuration;
        }
        public ActionResult Index()
        {
            String str = this.Configuration.GetConnectionString("SQL_AddressBook");
            CON_DAL dalCON = new CON_DAL();
            DataTable dt = dalCON.PR_ContactCategory_SelectAll(str);
            return View("MST_ContactCategoryList", dt);
        }
        public ActionResult Delete(int ContactCategoryID)
        {
            String str = this.Configuration.GetConnectionString("SQL_AddressBook");
            SqlConnection conn = new SqlConnection(str);
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "PR_ContactCategory_DeleteByPK";
            cmd.Parameters.AddWithValue("@ContactCategoryID", ContactCategoryID);
            DataTable dt = new DataTable();
            cmd.ExecuteNonQuery();
            conn.Close();

            return RedirectToAction("Index");
        }
        public IActionResult Add(int? ContactCategoryID)
        {
            if (ContactCategoryID != null)
            {
                String str = this.Configuration.GetConnectionString("SQL_AddressBook");
                SqlConnection conn = new SqlConnection(str);
                conn.Open();
                SqlCommand cmd = conn.CreateCommand();
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.CommandText = "PR_ContactCategory_SelectByPK";
                cmd.Parameters.Add("@ContactCategoryID", SqlDbType.Int).Value = ContactCategoryID;
                DataTable dt = new DataTable();
                SqlDataReader objSDR = cmd.ExecuteReader();
                dt.Load(objSDR);
                MST_ContactCategoryModel modelMST_ContactCategory = new MST_ContactCategoryModel();
                foreach (DataRow dr in dt.Rows)
                {
                    modelMST_ContactCategory.ContactCategoryID = (Convert.ToInt32(dr["ContactCategoryID"]));
                    modelMST_ContactCategory.ContactCategoryName = (Convert.ToString(dr["ContactCategoryName"]));
                    modelMST_ContactCategory.CreationDate = (Convert.ToDateTime(dr["CreationDate"]));
                    modelMST_ContactCategory.ModificationDate = (Convert.ToDateTime(dr["ModificationDate"]));
                }
                return View("MST_ContactCategoryAddEdit", modelMST_ContactCategory);
            }
            return View("MST_ContactCategoryAddEdit");
        }
    
        [HttpPost]
        public ActionResult Save(MST_ContactCategoryModel modelMST_ContactCategory)
        {
            String str = this.Configuration.GetConnectionString("SQL_AddressBook");
            SqlConnection conn = new SqlConnection(str);
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            if (modelMST_ContactCategory.ContactCategoryID == null)
            {
                cmd.CommandText = "PR_ContactCategory_Insert";
                cmd.Parameters.Add("@CreationDate", SqlDbType.DateTime).Value = DBNull.Value;
            }
            else
            {
                cmd.CommandText = "PR_ContactCategory_UpdateByPK";
                cmd.Parameters.Add("@ContactCategoryID", SqlDbType.Int).Value = modelMST_ContactCategory.ContactCategoryID;
            } 
            cmd.Parameters.Add("@ContactCategoryName", SqlDbType.NVarChar).Value = modelMST_ContactCategory.ContactCategoryName;
            cmd.Parameters.Add("@ModificationDate", SqlDbType.DateTime).Value = DBNull.Value;

            cmd.ExecuteNonQuery();
            conn.Close();
            return RedirectToAction("Index");
        }
    }
}

Areas/MST_ContactCategory/Views/MST_ContactCategory/MST_ContactCategoryAddEdit.cshtml
@{
    ViewData["Title"] = "ContactCategory Add/Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Multi_AddressBook.Areas.Models.MST_ContactCategoryModel
<div class="row">
    <div class="col-md-12">
        <h3> @TempData["ContactCategoryInsertMsg"]</h3>
        <form method="post" asp-controller="MST_ContactCategory" asp-action="Save" enctype="multipart/form-data">
            @Html.HiddenFor(x=>x.ContactCategoryID)
            <div class="form-group">
                <label>ContactCategory Name</label>
                <input type="text" asp-for="ContactCategoryName" class=form-control placeholder="Enter ContactCategory Name" />
            </div>
            
            <hr />
            <div class="center-button"><input class="btn btn-success" type="submit" value="Save"></div>
            <div class="center-button"><a asp-controller="LOC_Country" asp-action="Index" class="btn btn-danger">Cancel</a></div>
        </form>
    </div>
</div>

Areas/MST_ContactCategory/Views/MST_ContactCategory/MST_ContactCategoryList.cshtml
@{
    ViewData["Title"] = "Country List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using System.Data
@model DataTable
<div class="col-md-12">
    <div class="row">
        <div class=" col-md-10">
            <h3>Contact Category List</h3>
        </div>
        <div class="actions">
            <div class="btn-group btn-group-devided">
                <a asp-controller="MST_ContactCategory" asp-action="Add" class="btn green"><i class="fa fa-plus"></i>&nbsp;Add ContactCategory</a>
            </div>
        </div>
    </div>
</div>
<div class="portlet-body">
    <div class="pull-right">
        <div id="sample_1_filter" class="dataTables_filter">
            <label>Search Any&nbsp;<input type="" class="form-control input-sm input-small input-inline" placeholder="Search Anything" id="sample_1" aria-controls="sample_1"></label>
        </div>&nbsp;
    </div>
</div>
<table class="table table-striped table-bordered table-hover table-header-fixed dataTable" id="sample_1">
    <thead>
        <tr>
            
            <th>ContactCategory Name</th>&nbsp
            <th>CreationDate</th>&nbsp
            <th>ModificationDate</th>
            <th>Action</th>
           
        </tr>
    </thead>
    <tbody id="sample_2">
        @foreach (DataRow dr in Model.Rows)
        {
            <tr>
                
                <td>@dr["ContactCategoryName"]</td>&nbsp
                <td>@Convert.ToDateTime(dr["CreationDate"]).ToString("dd-mm-yyyy")</td>&nbsp
                <td>@Convert.ToDateTime(dr["ModificationDate"]).ToString("dd-mm-yyyy")</td>
                
                <td>
                    <form method="post" asp-controller="MST_ContactCategory" asp-action="Delete">
                        <input type="hidden" name="ContactCategoryID" value=" @Convert.ToInt32(dr["ContactCategoryID"].ToString()) " />
                        <button type="submit" class=" btn btn-danger btn-xs" onclick="return fun5();"><i class="fa fa-close"></i></button>
                        <a class=" btn btn-info btn-xs" asp-controller="MST_ContactCategory" asp-action="Add" asp-route-contactcategoryid="@Convert.ToInt32(dr["ContactCategoryID"])"><i class="fa fa-pencil"></i></a>
                    </form>
                </td>
            </tr>
        }

    </tbody>
</table>
@section Scripts
    {
    <script>
        $(document).ready(function () {
            $("#sample_1").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#sample_2 tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
        function fun5() {
            if (confirm("Are you sure you want to delete")) {
                return true;
            }
            else {
                return false;
            }
        }
    </script>
}