Controllers/LOC_CityController.cs
using AddressBook.DAL;
using AddressBook.Models;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Data.SqlClient;
using System.Reflection.Metadata.Ecma335;

namespace AddressBook.Controllers
{
    public class LOC_CityController : Controller
    {
        private IConfiguration Configuration;
        public LOC_CityController(IConfiguration _configuration)
        {
            Configuration = _configuration;
        }

        LOC_DAL dalLOC = new LOC_DAL();
        public ActionResult Index()
        {
            String str = this.Configuration.GetConnectionString("SQL_AddressBook");
            DataTable dt = dalLOC.PR_LOC_City_SelectAll(str);
            return View("LOC_CityList", dt);
        }

        public ActionResult Delete(int CityID)
        {
            String str = this.Configuration.GetConnectionString("SQL_AddressBook");
            if (Convert.ToBoolean(dalLOC.PR_LOC_City_Delete(str, CityID)))
                return RedirectToAction("Index");
            return View("Index");
        }
        public IActionResult Add(int? CityID)
        {
            
            String connectionstr1 = this.Configuration.GetConnectionString("SQL_AddressBook");
            DataTable dt2 = dalLOC.PR_LOC_State_SelectByDropdownList(connectionstr1);
            
            List<Areas.Models.LOC_CountryDropDownModel> list1 = new List<Areas.Models.LOC_CountryDropDownModel>();
            foreach (DataRow dr in dt2.Rows)
            {
                Areas.Models.LOC_CountryDropDownModel modelLOC_CountryDropDown = new Areas.Models.LOC_CountryDropDownModel();
                modelLOC_CountryDropDown.CountryID = (Convert.ToInt32(dr["CountryID"]));
                modelLOC_CountryDropDown.CountryName = (Convert.ToString(dr["CountryName"]));
                list1.Add(modelLOC_CountryDropDown);
            }
            ViewBag.CountryList = list1;
            
            List<Areas.Models.LOC_StateDropDownModel> list = new List<Areas.Models.LOC_StateDropDownModel>();
            ViewBag.StateList = list;

            if (CityID != null)
            {
                String str = this.Configuration.GetConnectionString("SQL_AddressBook");
                DataTable dt = dalLOC.PR_LOC_Country_SelectByPK(str, CityID);

                if (dt.Rows.Count > 0)
                {
                    LOC_CityModel modelLOC_City = new LOC_CityModel();
                    foreach (DataRow dr in dt.Rows)
                    {
                        modelLOC_City.CityID = (Convert.ToInt32(dr["CityID"]));
                        modelLOC_City.CityName = (Convert.ToString(dr["CityName"]));
                        modelLOC_City.CityCode = (Convert.ToString(dr["CityCode"]));
                        modelLOC_City.CreationDate = (Convert.ToDateTime(dr["CreationDate"]));
                        modelLOC_City.ModificationDate = (Convert.ToDateTime(dr["ModificationDate"]));
                        modelLOC_City.StateID = (Convert.ToInt32(dr["StateID"]));
                        modelLOC_City.CountryID = (Convert.ToInt32(dr["CountryID"]));
                    }
                    String connectionstr = this.Configuration.GetConnectionString("SQL_AddressBook");


                    SqlConnection conn1 = new SqlConnection(connectionstr);
                    conn1.Open();
                    SqlCommand cmd1 = conn1.CreateCommand();
                    cmd1.CommandType = CommandType.StoredProcedure;
                    cmd1.CommandText = "PR_LOC_State_SelectForDropDownByCountryID";
                    cmd1.Parameters.AddWithValue("@CountryID", modelLOC_City.CountryID);
                    DataTable dt1 = new DataTable();
                    SqlDataReader objSDR1 = cmd1.ExecuteReader();
                    dt1.Load(objSDR1);

                    List<Areas.Models.LOC_StateDropDownModel> list6 = new List<Areas.Models.LOC_StateDropDownModel>();
                    foreach (DataRow dr in dt1.Rows)
                    {
                        Areas.Models.LOC_StateDropDownModel vl = new Areas.Models.LOC_StateDropDownModel();
                        vl.StateID = (Convert.ToInt32(dr["StateID"]));
                        vl.StateName = (Convert.ToString(dr["StateName"]));
                        list6.Add(vl);
                    }
                    ViewBag.StateList = list;

                    return View("LOC_CityAddEdit", modelLOC_City);
                }
            }
            return View("LOC_CityAddEdit");
        }
        [HttpPost]
        public IActionResult Save(LOC_CityModel modelLoc_City)
        {
            string connectionString = this.Configuration.GetConnectionString("SQL_AddressBook");
            SqlConnection conn = new SqlConnection(connectionString);
            conn.Open();
            SqlCommand objCmd = conn.CreateCommand();
            objCmd.CommandType = CommandType.StoredProcedure;
            if(modelLoc_City.CityID == null)
            {
                objCmd.CommandText = "PR_LOC_City_Insert";
                objCmd.Parameters.Add("@CreationDate",SqlDbType.Date).Value = DBNull.Value;
            }
            else
            {
                objCmd.CommandText = "PR_LOC_City_UpdateByPK";
                objCmd.Parameters.Add("@CityID",SqlDbType.Int).Value = modelLoc_City.CityID;
            }
            objCmd.Parameters.Add("@CityName",SqlDbType.VarChar).Value = modelLoc_City.CityName;
            objCmd.Parameters.Add("@CityCode",SqlDbType.VarChar).Value = modelLoc_City.CityCode;
            objCmd.Parameters.Add("@StateID",SqlDbType.Int).Value = modelLoc_City.StateID;
            objCmd.Parameters.Add("@CountryID",SqlDbType.Int).Value = modelLoc_City.CountryID;
            objCmd.Parameters.Add("@ModificationDate",SqlDbType.Date).Value = DBNull.Value;
             
            if(Convert.ToBoolean(objCmd.ExecuteNonQuery()))
            {
                if(modelLoc_City.CityID == null)
                {
                    TempData["CityInsetMsg"] = "Record Inserted Successfully";
                }
                else
                {
                    TempData["CityInsetMsg"] = "Record Updated Successfully";
                }
            }
            conn.Close();
            
            return RedirectToAction("Index");
        }
        public ActionResult DropDownByCountry(int CountryID)
        {
            String connectionstr = this.Configuration.GetConnectionString("SQL_AddressBook");
           
           
            SqlConnection conn1 = new SqlConnection(connectionstr);
            conn1.Open();
            SqlCommand cmd1 = conn1.CreateCommand();
            cmd1.CommandType = CommandType.StoredProcedure;
            cmd1.CommandText = "PR_LOC_State_SelectForDropDownByCountryID";
            cmd1.Parameters.AddWithValue("@CountryID", CountryID);
            DataTable dt1 = new DataTable();
            SqlDataReader objSDR1 = cmd1.ExecuteReader();
            dt1.Load(objSDR1);
           
            List<Areas.Models.LOC_StateDropDownModel> list = new List<Areas.Models.LOC_StateDropDownModel>();
            foreach (DataRow dr in dt1.Rows)
            {
                Areas.Models.LOC_StateDropDownModel vl = new Areas.Models.LOC_StateDropDownModel();
                vl.StateID = (Convert.ToInt32(dr["StateID"]));
                vl.StateName = (Convert.ToString(dr["StateName"]));
                list.Add(vl);
            }
           
            var vmodel = list;
            return Json(vmodel);
        }
        public ActionResult Search(int CityID)
        {
            string str = this.Configuration.GetConnectionString("SQL_AddressBook");
            SqlConnection conn = new SqlConnection(str);
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "PR_LOC_City_Search";
            cmd.Parameters.AddWithValue("@CityName", Convert.ToString(HttpContext.Request.Form["CityName"]));
            cmd.Parameters.AddWithValue("@CityCode", Convert.ToString(HttpContext.Request.Form["CityCode"]));
            /*cmd.Parameters.AddWithValue("@CountryName", Convert.ToString(HttpContext.Request.Form["CountryName"]));
            cmd.Parameters.Add("@CountryName", SqlDbType.VarChar).Value = CountryName;
            cmd.Parameters.Add("@CountryCode", SqlDbType.VarChar).Value = CountryCode;*/
            DataTable dt = new DataTable();
            SqlDataReader objSDR = cmd.ExecuteReader();
            dt.Load(objSDR);

            return View("LOC_CityList", dt);
        }



    }
}

Views/CON_Contact/MAS_ContactAddEdit.cshtml
@{
    ViewData["Title"] = "Contact Add/Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model MAS_ContactModel
<div class="row">
    <div class="col-md-12">
        <h3> @TempData["ContactInsertMsg"]</h3>
        <form method="post" asp-controller="MAS_Contact" asp-action="Save" enctype="multipart/form-data">
            @Html.HiddenFor(x=>x.ContactID)
            @Html.HiddenFor(x=>x.PhotoPath)
            <div class="form-group">
                <label>Name</label>
                <input type="text" asp-for="ContactName" class=form-control placeholder="Enter Contact Name" />
            </div>
            <div class="form-group">
                <label>Mail</label>
                <input type="text" asp-for="ContactEmail" class=form-control placeholder="Enter EmailID" />
            </div>
            <div class="form-group">
                <label>Address</label>
                <input type="text" asp-for="ContactAddress" class=form-control placeholder="Enter Contact Address" />
            </div>
            <div class="form-group">
                <label>CountryName</label>
              <select class="form-control" asp-for="ContactCountryID" asp-items="@(new SelectList(ViewBag.CountryList,"CountryID","CountryName"))" onchange="fnOnStateChange();">
                    <option value="">Select Country</option>*
                </select>
            </div>
            <div class="form-group">
                <label>StateName</label>
                <select class="form-control" asp-for="ContactStateID" asp-items="@(new SelectList(ViewBag.StateList,"StateID","StateName"))" onchange="fnOnCityChange();">
                    <option value="0">Select State</option>
                </select>
            </div>
            <div class="form-group">
                <label>CityName</label>
                <select class="form-control" asp-for="ContactCityID" asp-items="@(new SelectList(ViewBag.CityList,"CityID","CityName"))">
                    <option value="0">Select City</option>
                </select>
            </div>
            <div class="form-group">
                <label>ContactCategory</label>
                <select class="form-control" asp-for="ContactCategoryID" asp-items="@(new SelectList(ViewBag.ContactCategoryList,"ContactCategoryID","ContactCategory"))">
                    <option value="0">Select ContactCategory</option>
                </select>
           </div>
            <div class="form-group">
                <label>Pincode</label>
                <input type="text" asp-for="ContactPincode" class=form-control placeholder="Enter Pincode" />
            </div><div class="form-group">
                <label>Gender</label>
                <input type="text" asp-for="ContactGender" class=form-control placeholder="Enter Gender" />
            </div><div class="form-group">
                <label>DateofBirth</label>
                <input type="date" asp-for="ContactDOB" class=form-control placeholder="Enter DateofBirth" />
            </div><div class="form-group">
                <label>Linkedin</label>
                <input type="text" asp-for="ContactLinkedIN" class=form-control placeholder="Enter Linkedin profile name" />
            </div>
            <div class="form-group">
                <label>PhotoPath</label>
                <input class="form-control" type="file" asp-for="File" placeholder="Upload File" />
            </div>
            <hr />
            <button type="submit" asp-controller="CON_Contact" asp-action="Save">Submit</button>
        </form>
    </div>
</div>
@section Scripts
    {
    <script>
        function fnOnStateChange() {
            var CountryID = $("#CountryID").val();

            if (CountryID !== "") {
                $("#StateID").empty();
                $("#StateID").append($("<option></option>").val("").html("Select State"));
                $.ajax(
                    {
                        type: "POST",
                        contentType: "application/json; charset=utf-8",
                        url: "@Url.Action("DropDownByCountry","LOC_City")" + "?&CountryID=" + CountryID,
                        data: {},
                        dataType: "json",
                        success: function (Result) {
                            $.each(Result,
                                function (key, value) {
                                    $("#StateID").append($("<option></option>").val(value.stateID).html(value.stateName));
                                }
                            );
                        },
                        error: function (r) {
                            alert("Error While Loading DropDown");
                        }
                    }
                );
            }
            else {
                $("#StateID").empty();
                $("#StateID").append($("<option></option>").val("").html("Select State"));
            }
        }
    </script>
    <script>
        function fnOnCityChange() {
            var StateID = $("#StateID").val();

            if (StateID !== "") {
                $("#CityID").empty();
                $("#CityID").append($("<option></option>").val("").html("Select City"));
                $.ajax(
                    {
                        type: "POST",
                        contentType: "application/json; charset=utf-8",
                        url: "@Url.Action("DropDownByState","CON_Contact")" + "?&StateID=" + StateID,
                        data: {},
                        dataType: "json",
                        success: function (Result) {
                            $.each(Result,
                                function (key, value) {
                                    $("#CityID").append($("<option></option>").val(value.cityID).html(value.cityName));
                                }
                            );
                        },
                        error: function (r) {
                            alert("Error While Loading DropDown");
                        }
                    }
                );
            }
            else {
                $("#CityID").empty();
                $("#CityID").append($("<option></option>").val("").html("Select City"));
            }
        }
    </script>

}

Views/CON_Contact/MAS_ContactList.cshtml
@{
    ViewData["Title"] = "Country List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using System.Data
@model DataTable
<div class="col-md-12">
    <div class="row">
        <div class=" col-md-10">
            <h3>Contact List</h3>
        </div>
        <div class="actions">
            <div class="btn-group btn-group-devided">
                <a asp-controller="CON_Contact" asp-action="Add" class="btn green"><i class="fa fa-plus"></i>&nbsp;Add Contact</a>
            </div>
        </div>
    </div>
</div>
<div class="portlet-body">
    <div class="pull-right">
        <div id="sample_1_filter" class="dataTables_filter">
            <label>Search Any&nbsp;<input type="" class="form-control input-sm input-small input-inline" placeholder="Search Anything" id="sample_1" aria-controls="sample_1"></label>
        </div>&nbsp;
    </div>
</div>
<table class="table table-striped table-bordered table-hover table-header-fixed dataTable" id="sample_1">
    <thead>
        <tr>
           <th>Action</th> 
            <th>ContactID</th>&nbsp
            <th>Name</th>&nbsp
            <th>Mail</th>&nbsp
            <th>Address</th>&nbsp
            
            <th>CityName</th>&nbsp
            
            <th>StateName</th>&nbsp
            
            <th>CountryName</th>&nbsp
            <th>Pincode</th>&nbsp
            <th>Gender</th>&nbsp
            <th>DateofBirth</th>&nbsp
            <th>Linkedin</th>
            <th>ContactCategory</th>
            <th>Photo</th>
            
        </tr>
    </thead>
    <tbody id="sample_2">
        @foreach (DataRow dr in Model.Rows)
        {
            <tr>
                <td>
                    <form method="post" asp-controller="CON_Contact" asp-action="Delete">
                        <input type="hidden" name="ContactID" value=" @Convert.ToInt32(dr["ContactID"].ToString()) " />
                         <button type="submit" class=" btn btn-danger btn-xs" onclick="return fun4();"><i class="fa fa-close"></i></button>
                            <a class=" btn btn-info btn-xs" asp-controller="CON_Contact" asp-action="Add" asp-route-contactid="@Convert.ToInt32(dr["ContactID"])"><i class="fa fa-pencil"></i></a>
                    </form>
                </td>
                <td>@dr["ContactID"]</td>&nbsp
                <td>@dr["Name"]</td>&nbsp
                <td>@dr["Mail"]</td>&nbsp
                <td>@dr["Address"]</td>&nbsp
                
                <td>@dr["CityName"]</td>&nbsp
               
                <td>@dr["StateName"]</td>&nbsp
                
                <td>@dr["CountryName"]</td>&nbsp
                <td>@dr["Pincode"]</td>&nbsp
                <td>@dr["Gender"]</td>&nbsp
                <td>@Convert.ToDateTime(dr["DateofBirth"]).ToString("dd-mm-yyyy")</td>&nbsp
                <td>@dr["Linkedin"]</td>
                <td>@dr["ContactCategory"]</td>
                <td><img src={@dr["PhotoPath"]} height="30px" width="30px" alt="img"></td>
            </tr>
        }

    </tbody>
</table>
@section Scripts
    {
    <script>
        $(document).ready(function () {
            $("#sample_1").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#sample_2 tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
        function fun4() {
            if (confirm("Are you sure you want to delete")) {
                return true;
            }
            else {
                return false;
            }
        }
    </script>
}